#!/usr/bin/env ruby
# -*- coding: utf-8 -*-
require "rubygems"
require "serialport"

if ARGV.empty?
  STDERR.puts 'ruby ruby-serialterm.rb /dev/tty/tty-usbdevice'
  exit 1
end

sp = SerialPort.new(ARGV.shift, 57600, 8, 1, SerialPort::NONE) # 9600bps, 8bit, stopbit1, parity-none

ir_data = ""

Thread.new do
  loop do
    recv = sp.gets.strip
    puts recv
    ir_data = recv.gsub(/^READ,/,"") if recv =~ /^READ,[\d,]+$/
  end
end

loop do
  loop do
    puts "read/write [r/w]"
    line = STDIN.gets.strip
    if line =~ /r/i
      puts "[READ]"
      sp.write "r"
    elsif line =~ /w/i
      puts "[WRITE]"
      "w#{ir_data}W".split(//).each do |c|
      sp.write c
      sleep 0.001
      end
    end
  end
end
